-- ============================================
-- نسخ هذا الكود في Supabase → SQL Editor → Run
-- ============================================

-- جدول المنتجات (مطابق للمتجر)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL UNIQUE,
  description TEXT DEFAULT '',
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  image TEXT DEFAULT '',
  stock INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول الطلبات (مطابق للمتجر)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name TEXT DEFAULT '',
  product_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','shipped','delivered','cancelled')),
  form_data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- فهارس للبحث السريع
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

-- تفعيل Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- سياسات: الجميع يقرأ المنتجات (لصفحة المتجر)
CREATE POLICY "السماح بقراءة المنتجات للجميع"
  ON products FOR SELECT
  USING (true);

-- سياسات: الجميع يضيف طلب (عند الضغط على زر الشراء)
CREATE POLICY "السماح بإضافة الطلبات للجميع"
  ON orders FOR INSERT
  WITH CHECK (true);

-- سياسات: الجميع يقرأ الطلبات (لوحة الإدارة تحتاج خدمة أخرى أو سنسمح للجميع مؤقتاً)
CREATE POLICY "السماح بقراءة الطلبات للجميع"
  ON orders FOR SELECT
  USING (true);

CREATE POLICY "السماح بتحديث الطلبات للجميع"
  ON orders FOR UPDATE
  USING (true);

-- (اختياري) سياسة إدراج/تحديث/حذف للمنتجات إذا أردت إدارة المنتجات من Supabase لاحقاً
CREATE POLICY "السماح بإدراج المنتجات للجميع"
  ON products FOR INSERT
  WITH CHECK (true);

CREATE POLICY "السماح بتحديث المنتجات للجميع"
  ON products FOR UPDATE
  USING (true);

CREATE POLICY "السماح بحذف المنتجات للجميع"
  ON products FOR DELETE
  USING (true);
